# Generated by Django 4.2 on 2025-03-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(default='cinetpay', max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('échoué', 'Échoué')], default='en_attente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
